apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  middle-ware: middle-ware-service
  mongo-url: mongodb+srv://mongo-user:OzKPxYYzbVoI2zv5@cluster0.jbylzmb.mongodb.net/?retryWrites=true&w=majority
