apiVersion: v1
kind: Secret
metadata:
  name: mongodb
type: Opaque
data:
  mongourl: bW9uZ29kYitzcnY6Ly9tb25nby11c2VyOjJoOXdQOFMzRVphdUxEaWlAY2x1c3RlcjAuamJ5bHptYi5tb25nb2RiLm5ldC8/cmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5
